### ISSUE TITLE
Prevent overwriting of filter ids in <defs></defs>

### ISSUE THREAD

**Issue by MDSLKTR** [FWeinb/grunt-svgstore#102]
When combining my SVGs into a symbol based Sprite, filters inside the defs block are renamed to include the filenames which then leads to a broken css filter link. Is it possible to turn renaming of for defs?

**Comment by arniebradfo** [comment]
I'm having the same issue.

a file named logo.svg:
`
<defs>
	<clipPath id="clipping-path">...</clipPath>
</defs>
<g clip-path="url(#clipping-path)">...</g>
`
will compile to:
`
<defs>
	<clipPath id="logo-clipping-path">...</clipPath>
</defs>
<g clip-path="url(#clipping-path)">...</g>
`
and the clippath will be broken.
the same thing will happen with masks or any other internal link using the url(#id) syntax.
