### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by visualcookie** [FWeinb/grunt-svgstore#103]
It looks like this repo has no active maintainer anymore, which is a bit sad. Are you getting back any time soon?

**Comment by FWeinb** [comment]
Sorry, currently I don't have much time to maintain this plugin because I don't use it. I would really like to get some help with this.

**Comment by MarkMurphy** [comment]
@FWeinb You should state that you're looking for collaborators to help maintain this project near the top of your readme.md

**Comment by FWeinb** [comment]
Sorry for the long phase of silence. I added it to the readme and would really like to get someone who would take over this.

**Comment by jonathantneal** [comment]
I’ve been recommending this plugin and I’ll be giving the source a few more passes. If I can help, I will.

**Comment by FWeinb** [comment]
Thanks! I added you as a collaborator. You should have commit rights now.

**Comment by CJohnDesign** [comment]
I want to help where I can. Thanks @FWeinb for your work so far, love the product!!

**Comment by roblevintennis** [comment]
I'd respectfully give feedback this be closed by OP or maintainer. I hadn't contributed for a while, and as I scanned down the issues list, I definitely saw this and wondered myself. I had faith having seen that @jonathantneal appears to sort of still maintain,  and coded up my PR, but I could see it dissuading others. This is a useful plugin and my company has used it in our SVG icon process for 3 years now. We've even had recent success with exporting from Sketch which simply requires adding the Sketch svgo compressor plugin to generate clean raw SVGs, and grunt-svgstore works fine!
