### ISSUE TITLE
Tags not closed in generated SVG

### ISSUE THREAD

**Issue by czebe** [FWeinb/grunt-svgstore#18]
If I have only one &lt;path&gt; element as the only child of SVG root, the generated svg will have &lt;path d="..." id="..."&gt; but no closing tag or trailing slash. I guess this is due to how cheerio handles non-html tags(?)

**Comment by SaadShahd** [comment]
Hello @FWeinb,

IE 11 logging to the console that: ``HTML1500: Tag cannot be self-closing. Use an explicit closing tag.``
and not rendering the SVG document.

the line we are taking about:
``<rect x="0.01" y="0.007" fill="#FFFFFF" width="216.681" height="216.81" />``
